# Canonical forms for common abbreviations and alternate spellings.
# Layer 6 normalisation applies these before deduplication.
SKILLS_ALIASES: dict[str, str] = {
    "js":          "JavaScript",
    "ts":          "TypeScript",
    "py":          "Python",
    "k8s":         "Kubernetes",
    "kube":        "Kubernetes",
    "tf":          "Terraform",
    "ml":          "Machine Learning",
    "ai":          "Artificial Intelligence",
    "dl":          "Deep Learning",
    "nlp":         "Natural Language Processing",
    "cv":          "Computer Vision",
    "oop":         "Object-Oriented Programming",
    "fp":          "Functional Programming",
    "rest":        "REST API",
    "graphql":     "GraphQL",
    "ci/cd":       "CI/CD",
    "devops":      "DevOps",
    "mlops":       "MLOps",
    "aws":         "Amazon Web Services",
    "gcp":         "Google Cloud Platform",
    "azure":       "Microsoft Azure",
    "postgres":    "PostgreSQL",
    "pg":          "PostgreSQL",
    "mongo":       "MongoDB",
    "redis":       "Redis",
    "es":          "Elasticsearch",
    "sk-learn":    "scikit-learn",
    "sklearn":     "scikit-learn",
    "xgb":         "XGBoost",
    "lgbm":        "LightGBM",
    ".net":        ".NET",
    "node":        "Node.js",
    "nodejs":      "Node.js",
    "vue":         "Vue.js",
    "react":       "React",
    "next":        "Next.js",
    "fastapi":     "FastAPI",
    "django":      "Django",
    "flask":       "Flask",
    "springboot":  "Spring Boot",
    "spring boot": "Spring Boot",
    # SAP variant spellings observed in production CVs
    "s4 hana":     "S/4 HANA",
    "s/4hana":     "S/4 HANA",
    "s4hana":      "S/4 HANA",
    "s4":          "S/4 HANA",
    "sap s4 hana": "SAP S/4 HANA",
    "sapui5":      "SAP UI5",
    "ui5":         "SAP UI5",
    "fiori":       "SAP Fiori",
    "sap fiori":   "SAP Fiori",
    "oops":        "OO ABAP",
    "oo abap":     "OO ABAP",
    "ooabap":      "OO ABAP",
    "abap/4":      "ABAP",
    "abap 4":      "ABAP",
    "btp":         "SAP BTP",
    "hana":        "SAP HANA",
    "sap hana":    "SAP HANA",
    "rap":         "RAP",
    "cds":         "CDS Views",
    "cds view":    "CDS Views",
    "odata":       "OData",
    "idoc":        "IDoc",
    "idocs":       "IDoc",
    "badi":        "BAdI",
    "amdp":        "AMDP",
    "alv":         "ALV",
    "bdc":         "BDC",
    "lsmw":        "LSMW",
    "smartforms":  "SmartForms",
    "smart forms": "SmartForms",
    "webdynpro":   "Web Dynpro",
    "web dynpro":  "Web Dynpro",
    "fpm":         "FPM",
    "ale":         "ALE",
    "rfc":         "RFC",
    "bapi":        "BAPI",
    "capm":        "CAPM",
    "cap":         "CAPM",
    "neptune":     "Neptune DXP",
}