# Canonical forms for common abbreviations and alternate spellings.
# Layer 6 normalisation applies these before deduplication.
SKILLS_ALIASES: dict[str, str] = {
    "js":          "JavaScript",
    "ts":          "TypeScript",
    "py":          "Python",
    "k8s":         "Kubernetes",
    "kube":        "Kubernetes",
    "tf":          "Terraform",
    "ml":          "Machine Learning",
    "ai":          "Artificial Intelligence",
    "dl":          "Deep Learning",
    "nlp":         "Natural Language Processing",
    "cv":          "Computer Vision",
    "oop":         "Object-Oriented Programming",
    "fp":          "Functional Programming",
    "rest":        "REST API",
    "graphql":     "GraphQL",
    "ci/cd":       "CI/CD",
    "devops":      "DevOps",
    "mlops":       "MLOps",
    "aws":         "Amazon Web Services",
    "gcp":         "Google Cloud Platform",
    "azure":       "Microsoft Azure",
    "postgres":    "PostgreSQL",
    "pg":          "PostgreSQL",
    "mongo":       "MongoDB",
    "redis":       "Redis",
    "es":          "Elasticsearch",
    "sk-learn":    "scikit-learn",
    "sklearn":     "scikit-learn",
    "xgb":         "XGBoost",
    "lgbm":        "LightGBM",
    ".net":        ".NET",
    "node":        "Node.js",
    "nodejs":      "Node.js",
    "vue":         "Vue.js",
    "react":       "React",
    "next":        "Next.js",
    "fastapi":     "FastAPI",
    "django":      "Django",
    "flask":       "Flask",
    "springboot":  "Spring Boot",
    "spring boot": "Spring Boot",
}